site_name: geodepoly
repo_url: https://github.com/ricfulop/geodepoly
theme:
  name: material
nav:
  - Home: index.md
  - API: api.md
  - Benchmarks: benchmarks.md
  - Paper mapping: paper_guide.md
  - Gallery: gallery.md
  - FAQ: faq.md
  - Troubleshooting: troubleshooting.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ricfulop/geodepoly

