site_name: geodepoly
repo_url: https://github.com/ricfulop/geodepoly
theme:
  name: material
nav:
  - Home: index.md
  - API: api.md
  - How it works: how_it_works.md
  - Examples: examples.md
  - Benchmarks: benchmarks.md
  - Bench presets: bench_presets.md
  - GeodeBench: geodebench.md
  - Batched kernels: batched.md
  - Performance: performance.md
  - Geode: geode.md
  - Layerings: layerings.md
  - Cubic & Quintic: cubic_quintic.md
  - Non-finance Adapters: non_finance_adapters.md
  - Paper mapping: paper_guide.md
  - AI Overview: ai_overview.md
  - AI Use Cases: ai_use_cases.md
  - AI Benchmarks: ai_benchmarks.md
  - Gallery: gallery.md
  - FAQ: faq.md
  - Troubleshooting: troubleshooting.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ricfulop/geodepoly

