name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,lint]
      - name: Test
        run: pytest -q --maxfail=1 --disable-warnings --cov=geodepoly --cov-report=term-missing
      - name: Lint (ruff)
        run: ruff check geodepoly
      - name: Format (black --check)
        run: black --check geodepoly
      - name: Type check (mypy)
        run: mypy geodepoly || true
