name: CLI Smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: geodepoly-solve works
        run: |
          geodepoly-solve --coeffs "[-6,11,-6,1]" --json > out.json
          python -c "import json; obj=json.load(open('out.json')); assert not (isinstance(obj, dict) and 'roots' in obj)"
      - name: geodepoly-bridge works
        run: |
          printf '{"coeffs":[-6,11,-6,1],"kwargs":{"method":"hybrid","resum":"auto"}}' | geodepoly-bridge > bridge.json
          python -c "import json; obj=json.load(open('bridge.json')); assert 'roots' in obj and isinstance(obj['roots'], list)"
